import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict
from dotenv import load_dotenv


_env_path = Path(__file__).resolve().parents[1] / "backend" / ".env"
if _env_path.exists():
    load_dotenv(_env_path)


@dataclass
class BotConfig:
    token: str = field(default_factory=lambda: os.getenv("BOT_TOKEN", ""))
    api_base: str = "https://api.telegram.org/bot"
    parse_mode: str = "HTML"
    disable_web_page_preview: bool = True
    mini_app_url: str = field(default_factory=lambda: os.getenv("MINI_APP_URL", "http://localhost:5173"))

    @property
    def enabled(self) -> bool:
        return bool(self.token)


REGION_CHANNELS: Dict[str, str] = {
    "москва": "@BplaScope_Moscow",
    "московская область": "@BplaScope_Moscow",
    "московский регион": "@BplaScope_Moscow",
    "санкт-петербург": "@BplaScope_Spb",
    "ленинградская область": "@BplaScope_Spb",
    "краснодарский край": "@BplaScope_Krasnodar",
    "ростовская область": "@BplaScope_Rostov",
    "воронежская область": "@BplaScope_Voronezh",
    "курская область": "@BplaScope_Kursk",
    "белгородская область": "@BplaScope_Belgorod",
    "брянская область": "@BplaScope_Bryansk",
    "калужская область": "@BplaScope_Kaluga",
    "смоленская область": "@BplaScope_Smolensk",
    "тверская область": "@+DGGhWE9cSiw5ODdi",
    "нижегородская область": "@+olGS7xmnD40xYjdi",
    "татарстан": "@+8E0NUKyKgawxM2Fi",
    "республика татарстан": "@+8E0NUKyKgawxM2Fi",
    "самарская область": "@BplaScope_Samara",
    "саратовская область": "@BplaScope_Saratov",
    "волгоградская область": "@BplaScope_Volgograd",
    "крым": "@BplaScope_Crimea",
    "республика крым": "@BplaScope_Crimea",
    "севастополь": "@BplaScope_Crimea",
    "тульская область": "@BplaScope_Tula",
    "липецкая область": "@BplaScope_Lipetsk",
    "орловская область": "@BplaScope_Orel",
    "псковская область": "@BplaScope_Pskov",
    "новгородская область": "@BplaScope_Novgorod",
    "вологодская область": "@BplaScope_Vologda",
    "ярославская область": "@BplaScope_Yaroslavl",
    "ивановская область": "@BplaScope_Ivanovo",
    "владимирская область": "@BplaScope_Vladimir",
    "рязанская область": "@BplaScope_Ryazan",
    "тамбовская область": "@BplaScope_Tambov",
    "пензенская область": "@BplaScope_Penza",
    "ульяновская область": "@BplaScope_Ulyanovsk",
    "кировская область": "@BplaScope_Kirov",
    "удмуртия": "@BplaScope_Udmurtia",
    "республика удмуртия": "@BplaScope_Udmurtia",
    "удмуртская республика": "@BplaScope_Udmurtia",
    "чувашия": "@BplaScope_Chuvashia",
    "республика чувашия": "@BplaScope_Chuvashia",
    "чувашская республика": "@BplaScope_Chuvashia",
    "марий эл": "@BplaScope_MariEl",
    "республика марий эл": "@BplaScope_MariEl",
    "мордовия": "@BplaScope_Mordovia",
    "республика мордовия": "@BplaScope_Mordovia",
    "астраханская область": "@BplaScope_Astrakhan",
    "калининградская область": "@BplaScope_Kaliningrad",
    "костромская область": "@BplaScope_Kostroma",
    "алтайский край": "@BplaScope_Altai",
    "амурская область": "@BplaScope_Amur",
    "ставропольский край": "@BplaScope_Stavropol",
    "республика адыгея": "@BplaScope_Adygea",
    "адыгея": "@BplaScope_Adygea",
    "оренбургская область": "@BplaScope_Orenburg",
    "республика башкортостан": "@BplaScope_Bashkortostan",
    "пермский край": "@BplaScope_Perm",
    "свердловская область": "@BplaScope_Ekaterinburg",
    "челябинская область": "@BplaScope_Chelyabinsk",
    "республика калмыкия": "@BplaScope_Kalmykia",
    "калмыкия": "@BplaScope_Kalmykia",
    "республика дагестан": "@BplaScope_Dagestan",
    "республика коми": "@BplaScope_Komi",
    "архангельская область": "@BplaScope_Arkhangelsk",
    "северный кавказ": "@BplaScope_NorthCaucasus",
    "курганская область": "@BplaScope_Kurgan",
    "республика карелия": "@BplaScope_Karelia",
    "тюменская область": "@BplaScope_Tyumen",
    "ханты-мансийский автономный округ": "@BplaScope_Khanty",
    "чеченская республика": "@BplaScope_Chechnya",
    "запорожская область": "@BplaScope_Zaporozhye",
    "херсонская область": "@BplaScope_Kherson",
    "донецк": "@BplaScope_Donetsk",
    "лнр": "@BplaScope_Lugansk",
    "приморский край": "@BplaScope_Primorye",
    "витебская область": "@BplaScope_Vitebsk",
    "могилевская область": "@BplaScope_Mogilev",
    "днепропетровская область": "@BplaScope_Dnepr",
    "северная осетия": "@BplaScope_Alania",
    "республика северная осетия": "@BplaScope_Alania",
    "кабардино-балкарская республика": "@BplaScope_Kabardino",
    "карачаево-черкесская республика": "@BplaScope_Karachay",
}

bot_config = BotConfig()

# Human-readable channel names for bot messages
CHANNEL_DISPLAY_NAMES: Dict[str, str] = {
    "@BplaScope_Moscow": "Bpla Scope Москва",
    "@BplaScope_Spb": "Bpla Scope СПБ",
    "@BplaScope_Krasnodar": "Bpla Scope Краснодар",
    "@BplaScope_Rostov": "Bpla Scope Ростов",
    "@BplaScope_Voronezh": "Bpla Scope Воронеж",
    "@BplaScope_Kursk": "Bpla Scope Курск",
    "@BplaScope_Belgorod": "Bpla Scope Белгород",
    "@BplaScope_Bryansk": "Bpla Scope Брянск",
    "@BplaScope_Kaluga": "Bpla Scope Калуга",
    "@BplaScope_Smolensk": "Bpla Scope Смоленск",
    "@BplaScope_Tver": "Bpla Scope Тверь",
    "@BplaScope_Nizhny": "Bpla Scope Нижний",
    "@BplaScope_Tatarstan": "Bpla Scope Татарстан",
    "@BplaScope_Samara": "Bpla Scope Самара",
    "@BplaScope_Saratov": "Bpla Scope Саратов",
    "@BplaScope_Volgograd": "Bpla Scope Волгоград",
    "@BplaScope_Crimea": "Bpla Scope Крым",
    "@BplaScope_Tula": "Bpla Scope Тула",
    "@BplaScope_Lipetsk": "Bpla Scope Липецк",
    "@BplaScope_Orel": "Bpla Scope Орёл",
    "@BplaScope_Pskov": "Bpla Scope Псков",
    "@BplaScope_Novgorod": "Bpla Scope Новгород",
    "@BplaScope_Vologda": "Bpla Scope Вологда",
    "@BplaScope_Yaroslavl": "Bpla Scope Ярославль",
    "@BplaScope_Ivanovo": "Bpla Scope Иваново",
    "@BplaScope_Vladimir": "Bpla Scope Владимир",
    "@BplaScope_Ryazan": "Bpla Scope Рязань",
    "@BplaScope_Tambov": "Bpla Scope Тамбов",
    "@BplaScope_Penza": "Bpla Scope Пенза",
    "@BplaScope_Ulyanovsk": "Bpla Scope Ульяновск",
    "@BplaScope_Kirov": "Bpla Scope Киров",
    "@BplaScope_Udmurtia": "Bpla Scope Удмуртия",
    "@BplaScope_Chuvashia": "Bpla Scope Чувашия",
    "@BplaScope_MariEl": "Bpla Scope Марий Эл",
    "@BplaScope_Mordovia": "Bpla Scope Мордовия",
    "@BplaScope_Astrakhan": "Bpla Scope Астрахань",
    "@BplaScope_Kaliningrad": "Bpla Scope Калининград",
    "@BplaScope_Kostroma": "Bpla Scope Кострома",
    "@BplaScope_Altai": "Bpla Scope Алтай",
    "@BplaScope_Amur": "Bpla Scope Амур",
    "@BplaScope_Stavropol": "Bpla Scope Ставрополь",
    "@BplaScope_Adygea": "Bpla Scope Адыгея",
    "@BplaScope_Orenburg": "Bpla Scope Оренбург",
    "@BplaScope_Bashkortostan": "Bpla Scope Башкортостан",
    "@BplaScope_Perm": "Bpla Scope Пермь",
    "@BplaScope_Ekaterinburg": "Bpla Scope Екатеринбург",
    "@BplaScope_Chelyabinsk": "Bpla Scope Челябинск",
    "@BplaScope_Kalmykia": "Bpla Scope Калмыкия",
    "@BplaScope_Dagestan": "Bpla Scope Дагестан",
    "@BplaScope_Komi": "Bpla Scope Коми",
    "@BplaScope_Arkhangelsk": "Bpla Scope Архангельск",
    "@BplaScope_NorthCaucasus": "Bpla Scope Сев.Кавказ",
    "@BplaScope_Kurgan": "Bpla Scope Курган",
    "@BplaScope_Karelia": "Bpla Scope Карелия",
    "@BplaScope_Tyumen": "Bpla Scope Тюмень",
    "@BplaScope_Khanty": "Bpla Scope Ханты",
    "@BplaScope_Chechnya": "Bpla Scope Чечня",
    "@BplaScope_Zaporozhye": "Bpla Scope Запорожье",
    "@BplaScope_Kherson": "Bpla Scope Херсон",
    "@BplaScope_Donetsk": "Bpla Scope Донецк",
    "@BplaScope_Lugansk": "Bpla Scope Луганск",
    "@BplaScope_Primorye": "Bpla Scope Приморье",
    "@BplaScope_Vitebsk": "Bpla Scope Витебск",
    "@BplaScope_Mogilev": "Bpla Scope Могилёв",
    "@BplaScope_Dnepr": "Bpla Scope Днепр",
    "@BplaScope_Alania": "Bpla Scope Алания",
    "@BplaScope_Kabardino": "Bpla Scope Кабардино",
    "@BplaScope_Karachay": "Bpla Scope Карачай",
}
